version: "2.5"

services:
  prod:
    build: .
    container_name: daily-chaan-prod
    ports:
      - "80:3000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REDIS_URL=redis-container
      - PORT=3000
    env_file:
      - .env
    command: npm run start
    depends_on: 
      - redis
  redis:
    image: redis
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"